name: virtuetracker
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/virtuous_circle_outline.png
    - assets/images/googleLogo.png
    - assets/images/facebookLogo.png
    - assets/images/appleLogo.png

